### ISSUE TITLE
Grid Search

### ISSUE THREAD

**Issue by ShaikhaTheGreen** [caio-davi/PSO-PINN#2]
Dear developers, thank you for the great tool!

I noticed in the paper that you had used Grid Search to explore the most appropriate alpha, Beta, c1, c2, and initialization. How can I perform this for a new equation other than the ones mentioned in the paper?

Thanks for taking the time to read this question!
--Shaikhah

**Comment by caio-davi** [comment]
Well, it will be very time costly and computationally expensive. It took me a few days running over GPUs in the Texas A&M HPC Cluster. But basically, I just did a simple grid search using a bunch of python and bash scripts (required to call the cluster's process manager).

**Comment by caio-davi** [comment]
Closing, as it is not an issue related to the PSO-PINN.
